### ISSUE TITLE
Badly named methods

### ISSUE THREAD

**Issue by AntoineMazuyer** [GEOS-DEV/GEOS#917] opened 2020-05-01 09:03 UTC
Some functions are badly named
e.g.

https://github.com/GEOSX/GEOSX/blob/b1224b9d6f190bb6f44025c687b3c46f18f36c28/src/coreComponents/mesh/EdgeManager.hpp#L142-L146

that are returning an index, not a list.

Maybe we have to do something more general with the methods naming (ensuring CamelCase, checking if the name of the method is right etc.)

**Comment by TotoGaz** [comment] 2023-06-22 21:41
The issue is a bit too broad to bit assessed. I'll close it for now.

**Closed by TotoGaz** 2023-06-22 21:41 UTC
Labels: type: cleanup / refactor
