### ISSUE TITLE
Error at mesh loading in serial with same mesh loaded in parallel

### ISSUE THREAD

**Issue by philippechehade** [GEOS-DEV/GEOS#2262] opened 2023-02-01 17:41 UTC
I have a model that was launched in parallel and was successfully initialized. 
When trying to launch this model in serie (n=1), the below error was obtained
![image](https://user-images.githubusercontent.com/119044257/216120499-c0bd9c7f-9d4e-4f91-acfe-1e9971a456fc.png)

While I understand that the grid might be too big for a simulation on one core, however, the issue makes the user think that the problem comes from the grid. Whereas this same grid was successfully read by GeosX when working with several cores. 
It's misleading to read that the data set needs cleaning 
@jeannepellerin

**Comment by TotoGaz** [comment] 2023-02-01 17:59
@philippechehade can you check if you have duplicated nodes?

**Comment by jeannepellerin** [comment] 2023-02-01 18:02
The mesh was laoding fine on 64 ranks. It is a rather big mesh. Same model than issue #2263

**Comment by dkachuma** [comment] 2023-02-02 21:29
@philippechehade Is this the same region setup as #2263?

**Comment by dkachuma** [comment] 2023-02-02 22:07
I get the following from `mesh_doctor`
```
[2023-02-02 16:06:51,689][ERROR] You have 145784 collocated nodes (tolerance = 1e-06).
[2023-02-02 16:06:51,740][ERROR] You have no element with duplicated support nodes.
```
I'm buffled as to how this works in parallel

**Comment by klevzoff** [comment] 2023-02-03 00:23
In parallel we are using `vtkAppendFilter` when joining redistributed mesh pieces, which as a side effect also eliminates duplicate nodes. In a serial run that code path is not invoked (it requires at least 2 mesh partitions to be merged). Once we upgrade VTK version to latest, we might be able to use an additional filter to clean the mesh internally, but for now it is suggested to do this in Paraview or another tool.

**Comment by TotoGaz** [comment] 2023-02-03 04:40
@dkachuma I'm not sure of what's going on there, but you may give a try at the `useGlobalIds` feature (see [here](https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/CompleteXMLSchema.html#element-vtkmesh)) that can be used to distinguish between nodes.
If your current mesh does not have any of those fields, you may try the `--generate_global_ids` option of `mesh_doctor` that should generate some for you.

**Comment by dkachuma** [comment] 2023-02-03 20:55
The collocated nodes in the actual mesh for this bug are actually spurious in that they are for cells in the mesh that are not considered in the solvers i.e. not included in a `CellElementRegion`. In a serial run, the points are still checked but in a parallel run, they appear to be filtered as @klevzoff has pointed out.

I have reproduced this and I have attached the case with 3 meshes [collocated.tar.gz](https://github.com/GEOSX/GEOSX/files/10582714/collocated.tar.gz):
- `grid.00.vtu` - This has irrelevant collocated nodes. I have simply taken an OK mesh and added a bunch of collocated points at the end far away from the actual mesh. And sure enough this reproduces the behaviour of the original model. There's an error in serial but parallel runs are OK.
- `grid.01.vtu` - This has a few (4) collocated nodes within the region of interest. Again this fails in serial. This also fails in parallel with 2 mpi processes but runs in parallel with 4 mpi processes.
- `grid.02.vtu` - This has more (8) collocated nodes within the region of interest. This fails in both serial and in parallel (2 mpi processes and 4 mpi processes).

So it looks to me that the failure on collocated nodes is dependent on the partitioning. You might get a "lucky" partition that allows the simulation to proceed.

For the actual model in this case, I would go for cleaning the mesh. I don't think the collocated nodes here are intentional. So I don't see the need to externally assign global ids.

As to the general question of what to do when we have collocated nodes, maybe we need to be consistent. So we either fail in all cases (all parallel configurations) or clean up the mesh in all cases. I'm not sure which is the correct behaviour.

**Comment by herve-gross** [comment] 2023-02-07 18:44
@TotoGaz can you test @dkachuma 's models, and after that depending on what we find, we may need  @jeannepellerin's help coordinating a fix with Kitware.

**Comment by jeannepellerin** [comment] 2023-02-15 18:19
Thanks @klevzoff and @dkachuma for the explanation. 

I agree with @dkachuma that the behavior should be the same in all cases. Since the tool to fix the issue is provided (mesh_doctor) and we want to be sure that users check their meshes, I think it is ok to fail.

**Comment by TotoGaz** [comment] 2023-02-15 19:11
> Since the tool to fix the issue is provided (mesh_doctor)

Were you able to test? The `useGlobalIds` is an assumption, but I'm not sure it actually solves the issue.

**Comment by TotoGaz** [comment] 2023-04-05 16:54
Hello, I have a little time to get back on this issue.

I understand that `mesh_doctor` can consistently indicate the duplicated nodes.
Having a consistent failure behavior in C++ would be great, but having such a check in `geos/C++` would actually duplicate the efforts that were done in `mesh_doctor`.
And this, for no real functional added-value w.r.t the users.
(When I say "duplicate", I believe it's more than this).

So what do we want to do with this issue?
I think that we should close it _as is_, because we already provide tools to face this kind of issues.

What's your take?

**Comment by untereiner** [comment] 2023-06-15 12:19
@jeannepellerin ?

**Comment by cssherman** [comment] 2023-06-29 16:51
@TotoGaz - perhaps we can add some text in the error message, where we ask people to check their mesh with MeshDoctor?

**Comment by paveltomin** [comment] 2023-09-20 23:04
anyone, hello?

**Comment by jeannepellerin** [comment] 2023-10-24 09:48
Thank you all for your comments and thanks to Dick for the detailed analysis. I agree that we need to be consistent.
In theory, users should always check their mesh with mesh_doctor. In practice, they may skip it (even more so if magic happens to fix it). The main benefit of failing in all cases is that it is an important step to ensure that the input mesh is not modified (as expected for many applications), and to ensure that all users check their meshes. The drawback is clear.

Let's complete the error message and ask the user to check the mesh in PR#2450 that is almost ready.

**Comment by paveltomin** [comment] 2024-02-27 18:26
https://github.com/GEOS-DEV/GEOS/pull/2450 merged, closing this one

**Closed by paveltomin** 2024-02-27 18:26 UTC
Labels: type: bug
