### ISSUE TITLE
Removing PAMELA support from GEOSX

### ISSUE THREAD

**Issue by TotoGaz** [GEOS-DEV/GEOS#2188] opened 2022-11-30 17:45 UTC
Since we're moving to `vtk`, there's no more need to compile PAMELA it and maintain the wrappers.
This issue is another version of https://github.com/GEOSX/GEOSX/issues/2015, everyone's welcome to modify it.

Here are the items to suppress PAMELA from the code base, split in 3 bundles

Preliminary work to make PAMELA disappear from the features. Each tick box can have its own PR.
- [x] Upgrade documentation. PAMELA **features** should be documented the `vtk` way.
The way to build GEOSX using PAMELA should still be documented: PAMELA's still there.
Done in https://github.com/GEOSX/GEOSX/pull/2203
- [x] Reimplement the relevant PAMELA integrated tests (_i.e._ tutorial 2) using `vtk`
Done in https://github.com/GEOSX/GEOSX/pull/2203
- [x] Update the integrated tests using a PAMELA feature.
This was already done by @castelletto1 in https://github.com/GEOSX/GEOSX/pull/1992

Secondary steps will actually remove PAMELA from the code base.
Most probably all the tick boxes need to be addressed in the same PR, but maybe removing PAMELA as a submodule can be done separately.
- [x] Update/suppress code (C++ Wrappers, `CMakeLists.txt`).
- [x] Suppress the tests dedicated to validating PAMELA itself.
- [x] Upgrade documentation. References to PAMELA in the build should be removed. PAMELA should not appear anymore.
- [x] Remove PAMELA from the submodules.
- [x] Update travis accordingly (cloning the submodules and the `check_submodules` step).
All tickboxes done in #2204 

Final cleanup.
- [x] Archive the PAMELA repository?
- [x] ~~Do we want to add a script to convert from `gmsh` to `vtk`? Relying on `meshio` for example?~~ We're not doing this eventually.

~~- [ ] Add tutorial(s) to the integrated tests.~~

**Comment by CusiniM** [comment] 2022-12-08 00:45
if we do add a script to conver `gmsh` to `vtk`, I think it should be done in [here](https://github.com/GEOSX/GEOSX/tree/develop/src/coreComponents/python/modules/geosx_mesh_tools_package/geosx_mesh_tools)

**Comment by TotoGaz** [comment] 2022-12-08 02:58
> if we do add a script to conver `gmsh` to `vtk`, I think it should be done in [here](https://github.com/GEOSX/GEOSX/tree/develop/src/coreComponents/python/modules/geosx_mesh_tools_package/geosx_mesh_tools)

I was considering merging all the meshing tools (including generation tools like those for fractures) into `mesh_doctor` to get one unique source of scripting, unit testing, deployment with dependencies, etc.
What do you think?

**Comment by CusiniM** [comment] 2022-12-14 20:25
> > if we do add a script to conver `gmsh` to `vtk`, I think it should be done in [here](https://github.com/GEOSX/GEOSX/tree/develop/src/coreComponents/python/modules/geosx_mesh_tools_package/geosx_mesh_tools)
> 
> I was considering merging all the meshing tools (including generation tools like those for fractures) into `mesh_doctor` to get one unique source of scripting, unit testing, deployment with dependencies, etc. What do you think?

yeah, sounds good to me. I just think that we should unify them into a single "package". I don't have strong opinions about what the name/form of this package should be.

**Comment by TotoGaz** [comment] 2023-01-11 01:35
@castelletto1 @joshua-white @herve-gross
What are you wishes w.r.t. the final clean-up stage of this issue?
Specially about the `gmsh` to `vtk` conversion.

**Comment by castelletto1** [comment] 2023-01-11 18:55
I vote for archiving the PAMELA repository. I know we used to support `msh` external meshes, but I don't know how much of a priority the `gmsh` to `vkt` conversion is.

What I would probably do before closing the issue is to integrate [Tutorial 2: External Meshes](https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/tutorials/step02/Tutorial.html#tutorial-2-external-meshes) with an example in which the boundary of the domain where boundary conditions are prescribed cannot be selected using a Box (example a cube that is not aligned with the x-, y-, z-axis) and requires the definitions of faces with an attribute.

**Comment by TotoGaz** [comment] 2023-01-11 19:57
I'm fine with your propositions.

It's true that making yet another version of a wrapper to convert `gmsh` to `vtk` is surely not a priority.
Indeed, we may decide not to do it, in order not to be accountable for anything from the backend lib we're wrapping.

If you can push the update/push the integrated case, then I think we'll be done with this issue.

**Comment by castelletto1** [comment] 2023-01-11 22:06
Should we delete the following meshes: (i) [toy_model.GRDECL](https://github.com/GEOSX/GEOSX/blob/develop/src/coreComponents/unitTests/meshTests/toy_model.GRDECL), (ii) [toy_model.msh](https://github.com/GEOSX/GEOSX/blob/develop/src/coreComponents/unitTests/meshTests/toy_model.msh)? Without PAMELA we can't do much with them.

**Comment by TotoGaz** [comment] 2023-01-11 23:38
Should we convert them for further usage?

**Comment by TotoGaz** [comment] 2023-01-25 23:57
@rrsettgast Can you archive the PAMELA repository?

**Comment by untereiner** [comment] 2023-06-15 12:34
@TotoGaz Can this issue be closed ? (is it that bad Pamela is not archived)

**Comment by TotoGaz** [comment] 2023-06-16 15:35
Surely the `Add tutorial(s) to the integrated tests.` action can be moved to another issue, but I don't think we should close it before PAMELA is archived... 🤷 
@rrsettgast do you have time for this?

**Comment by rrsettgast** [comment] 2023-06-16 18:57
@TotoGaz Done

**Closed** 2023-06-16 19:02 UTC
Labels: type: cleanup / refactor

**Comment by rnelias** [comment] 2025-02-28 00:14
Sorry if it's not the right place to post this question.

I know the issue is already closed but I'm a newcomer to GEOS and recently started to follow the tutorials to implement SPE11 tests.

Afaik, PALOMA had been used to load Eclipse meshes into GEOS but, since it's not (officially?) supported anymore, should I use the Gmsh file and convert it to vtk (can be done in paraview)? My concern is about properties fields like porosity, saturation, permeability, etc... that were available in the Eclipse files.
