### ISSUE TITLE
Use `sccache` to speed our `CI/CD`

### ISSUE THREAD

**Issue by TotoGaz** [GEOS-DEV/GEOS#2579] opened 2023-07-15 00:28 UTC
@klevzoff proposed to use [sccache](https://github.com/mozilla/sccache) to speed up our builds. Let's test it!
- [x] Test on one build with a GCP bucket.
  - [x] Manage to build using `sccache`.
  - [x] Manage to build on CI using `sccache`.
  - [x] Manage GCP protections (upload & download).
- [x] Expand to all the builds if successful. (Out of the box there seems to be something weird with `CUDA`)
- [x] Seamlessly embed the `sccache` feature in the workflow (`USE_SCCACHE`, etc.)
- [ ] What about `SCCACHE_C_CUSTOM_CACHE_BUSTER` (see [doc](https://github.com/mozilla/sccache/blob/main/README.md#separating-caches-between-invocations))?
- [ ] Maybe reorganize our workflows since we're able to be really fast without our current build splits?
- [ ] Potentially use an Azure bucket to reduce egress.

Relates to https://github.com/GEOS-DEV/GEOS/pull/2760 and https://github.com/GEOS-DEV/thirdPartyLibs/pull/245

**Comment by klevzoff** [comment] 2023-07-15 01:30
To give credit for the idea, I was recently listening to a talk by folks from https://github.com/NVIDIA/cccl on their new CI setup, and I was impressed by a live demo of reproducing a CI build failure in a local devcontainer in less than 30 seconds. `sccache` was a key part of that, since build artifacts produced by CI can be shared with local builds too.

For us the main use case comes from the fact that most PRs only change a small subset of files (say, flow solvers but not mechanics, or sometimes even just test cases/examples), and all kernel instantiations don't actually need to be recompiled and can be cached across CI builds.

**Comment by TotoGaz** [comment] 2023-07-15 18:12
> To give credit for the idea, I was recently listening to a talk by folks from https://github.com/NVIDIA/cccl on their new CI setup

Go work for them 😉 🤣 ! We've all understood 🤔 🤣 

> and I was impressed by a live demo of reproducing a CI build failure in a local devcontainer in less than 30 seconds. `sccache` was a key part of that, since build artifacts produced by CI can be shared with local builds too.

I'm sure we're quite close to this as well!

> For us the main use case comes from the fact that most PRs only change a small subset of files (say, flow solvers but not mechanics, or sometimes even just test cases/examples), and all kernel instantiations don't actually need to be recompiled and can be cached across CI builds.

I'd say that the strongest use case is when devs eventually polish their PR, bringing tiny changes or comments here and there.
Not recompiling everything from one build to another build from the same PR can be quite efficient!

**Comment by TotoGaz** [comment] 2023-10-17 04:46
For the record, our `CUDA` builds are poorly cached on `CI` with status at the end of the build being:
```
Compile requests                    819
Compile requests executed            35
Cache hits                           35
Cache hits (C/C++)                   35
Cache misses                          0
Cache timeouts                        0
Cache read errors                     0
Forced recaches                       0
Cache write errors                    0
Compilation failures                  0
Cache errors                          0
Non-cacheable compilations            0
Non-cacheable calls                 784
Non-compilation calls                 0
Unsupported compiler calls            0
Average cache write               0.000 s
Average compiler                  0.000 s
Average cache read hit            0.144 s
Failed distributed compilations       0
```
That is a huge amount of `Non-cacheable calls`.
I suspect some language forcing issue...
I should try to run it interactively for better understanding.

**Comment by klevzoff** [comment] 2023-10-17 05:51
Could you rerun the build by adding a dummy commit? I would expect the cache hit ratio to be 100% on repeated runs, just the like with the non-CUDA builds. In the end, once this is merged and `sccache` is activated in every PR, hit rate across multiple PRs should hopefully be very high.

**Comment by TotoGaz** [comment] 2023-10-17 14:39
I've already re-run everything multiple times from the CI.
I've just retriggered the build one more time (from the CI, no new commit).

I think there must be something specific to our `CUDA` build because the same pattern/code works perfectly with CPU builds.
For CPU, I can run a first build, with a lot of (all?) misses. Then if I run the same build again (from the CI, no new commit), I have 100% cache hits.

I think there may be something weird with our CLI options (it says `multiple input files`...), which is not properly managed by `sccache` which then decides to throw in the towel.

**Closed** 2023-11-02 20:59 UTC
Labels: type: feature

**Comment by TotoGaz** [comment] 2023-11-27 18:36
Note that https://github.com/GEOS-DEV/GEOS/pull/2829 upgrades the version of `sccache` and the GPU builds are now properly using the caching mechanism.
